name: CI Slack Notify
description: Post your build information to Slack.
inputs:
  slackBotToken:
    description: TBD
    required: true
  slackChannel:
    description: Name or ID of the channel where notification will be sent.
    required: true
runs:
  using: node12
  main: dist/index.js
