name: CI Slack Notify
description: Post your build information to Slack.
inputs:
  slackBotToken:
    description: TBD
    required: true
  slackChannel:
    description: Name or ID of the channel where notification will be sent.
runs:
  using: 'node12'
  pre: 'dist/pre.js'
