name: Slack Web API client
description: Provides access to Slack WebAPI
inputs:
  slackToken:
    description: Slack bot user token.
    required: true
  slackAPIMethod:
    description: Name of the Slack web-api method to call
    required: true
    default: chat.postMessage
  slackMethodArgs:
    description: JSON-formated arguments passed to method
    required: true
    default: "{}"
outputs:
  slackMethodResults:
    description: JSON-formated method results
runs:
  using: node12
  main: dist/index.js
