name: Slack Web API client
description: TBD
inputs:
  slackToken:
    description: TBD
    required: true
  slackAPIMethod:
    description: |
      Name of the Slack web-api method to call
    required: true
    default: chat.postMessage
  slackMethodArgs:
    description: TBD
    required: true
    default: "{}"
outputs:
  slackMethodResults:
    description: TBD
runs:
  using: node12
  main: dist/index.js
